/*!
 * @file
 * @brief Generated by the MCUXpresso clocks tool.
 */

#include "clock.h"
#include "fsl_clock.h"

#define BOARD_BOOTCLOCKRUN_CORE_CLOCK 48000000U

extern uint32_t SystemCoreClock;

static const ics_config_t icsConfig_BOARD_BootClockRUN = {
  .icsMode = kICS_ModeFEI, /* FEI - FLL Engaged Internal */
  .irClkEnableMode = kICS_IrclkEnable, /* ICSIRCLK enabled, ICSIRCLK disabled in STOP mode */
  .bDiv = 0x0U, /* Bus clock divider: divided by 1 */
  .rDiv = 0x3U, /* FLL external reference clock divider: divided by 256 */
};

static const sim_clock_config_t simConfig_BOARD_BootClockRUN = {
  .outDiv1 = 0x0U, /* DIV1 clock divider: divided by 1 */
  .outDiv2 = 0x1U, /* DIV2 clock divider: divided by 2 */
  .outDiv3 = 0x0U, /* DIV3 clock divider: divided by 1 */
  .busClkPrescaler = 0x0U, /* bus clock optional prescaler */
};

void clock_init(void)
{
  /* Set the system clock dividers in SIM to safe value. */
  CLOCK_SetSimSafeDivs();
  /* Set ICS to FEI mode. */
  CLOCK_BootToFeiMode(icsConfig_BOARD_BootClockRUN.bDiv);
  /* Configure the Internal Reference clock (ICSIRCLK). */
  CLOCK_SetInternalRefClkConfig(icsConfig_BOARD_BootClockRUN.irClkEnableMode);
  /* Set the clock configuration in SIM module. */
  CLOCK_SetSimConfig(&simConfig_BOARD_BootClockRUN);
  /* Set SystemCoreClock variable. */
  SystemCoreClock = BOARD_BOOTCLOCKRUN_CORE_CLOCK;
}
