/*!
 * @file
 * @brief
 */

#include "MKE06Z4.h"
#include "clock.h"

void clock_init(void)
{
  // Register values generated by MCUXpresso
  ICS->C1 = ICS_C1_CLKS(0) | ICS_C1_IRCLKEN(1) | ICS_C1_IREFS(1) | ICS_C1_IREFSTEN(0) | ICS_C1_RDIV(3);
  ICS->C2 = ICS_C2_BDIV(0);
  OSC->CR = OSC_CR_HGO(0) | OSC_CR_OSCEN(1) | OSC_CR_OSCOS(0) | OSC_CR_OSCSTEN(0) | OSC_CR_RANGE(1);
  SIM->CLKDIV = SIM_CLKDIV_OUTDIV1(0) | SIM_CLKDIV_OUTDIV2(1) | SIM_CLKDIV_OUTDIV3(0);

  SystemCoreClockUpdate();
}
