name: Target Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-11, macos-latest]

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - uses: SimenB/github-actions-cpu-cores@v1

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - run: make -j${{ steps.cpu-cores.outputs.count }} -f target.mk
